export const ACTION_SEARCH = 'ACTION_SEARCH';
export const ACTION_SEARCH_RESET = 'ACTION_SEARCH_RESET';
export const ACTION_VIEW_MODE = 'ACTION_VIEW_MODE';
export const ACTION_TRACK_SET = 'ACTION_TRACK_SET';
export const ACTION_TRACK_EMBED = 'ACTION_TRACK_EMBED';
export const ACTION_CONTAINER_SET = 'ACTION_CONTAINER_SET';

export const REQUEST_STATUS_LOAD = 'REQUEST_STATUS_LOAD';
export const REQUEST_STATUS_SUCCESS = 'REQUEST_STATUS_SUCCESS';
export const REQUEST_STATUS_FAIL = 'REQUEST_STATUS_FAIL';

export const VIEW_MODE_LIST = 'VIEW_MODE_LIST';
export const VIEW_MODE_TILES = 'VIEW_MODE_TILES';

export const CONTAINER_SEARCH = 'CONTAINER_SEARCH';
export const CONTAINER_TRACK = 'CONTAINER_TRACK';